import type { NextPage } from "next";
import React, { useState, useEffect } from "react";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import {
	GetCookie,
	GetSessionStorage,
	GetLocalStorage,
} from "../components/getCookie/getCookie";
import Sidebar from "../components/Sidebar/Sidebar";
import Navbar from "../components/Navbar/Navbar";
import { useRouter } from "next/router";
import { GetServerSideProps } from "next";

export default function Home() {
	const router = useRouter();
	useEffect(() => {
		console.log(GetCookie("role"));
		console.log(GetSessionStorage("role"));
		if (
			GetCookie("role") === undefined ||
			GetCookie("role") === "" ||
			!GetCookie("role")
		) {
			router.replace("/signin");
		}
	}, []);

	return (
		<div className="w-[100vw] h-[100vh] m-0 p-0 bg-bgColor">
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<div className="w-full h-full flex flex-row ">
				<Sidebar />
				<div className="w-full ">
					<Navbar />
				</div>
			</div>
		</div>
	);
}

export const getServerSideProps: GetServerSideProps = async (context: any) => {
	const cookie = context.req.cookies;

	if (cookie.role === undefined || cookie.role === "" || !cookie.role) {
		return {
			redirect: {
				destination: "/signin",
				permanent: false,
			},
		};
	}
	return {
		props: {},
	};
};
