import type { NextPage } from "next";
import React, { useState, useEffect } from "react";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import {
	GetCookie,
	GetSessionStorage,
} from "../components/getCookie/getCookie";
import Sidebar from "../components/Sidebar/Sidebar";
import Navbar from "../components/Navbar/Navbar";

export default function Teachers() {
	useEffect(() => {
		console.log(GetCookie("role"));
		console.log(GetSessionStorage("role"));
	}, []);

	return (
		<div className="w-100 h-100 m-0 p-0 bg-bgColor">
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<div className="w-100 h-100 flex flex-row ">
				<Sidebar />
				<div>
					<Navbar />
				</div>
			</div>
		</div>
	);
}
